apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  project: default
  source:
    chart: banzaicloud-stable/vault
    helm:
      values: |
        ingress:
          enabled: true
          hosts:
            - vault.management-b.pomelo.health
          annotations:
             kubernetes.io/ingress.class: nginx

    repoURL: http://kubernetes-charts.banzaicloud.com/branch/master
    targetRevision: 1.13.0
  syncPolicy:
    automated:
      prune: true
      selfHeal: true